# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: Paardenvechters
author: Thimo

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: force

# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: book.tex

# Information about where the book exists on the web
repository:
  url: https://github.com/Thimomo/Paardenvechters  # Ensure this is correct
  path_to_book: docs  # Point to the docs directory
  branch: main

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  use_issues_button: true
  use_repository_button: true
  baseurl: "/Paardenvechters"

# Add launch buttons
launch_buttons:
  binderhub_url: ""
  colab_url: "https://colab.research.google.com"
  jupyterhub_url: ""

sphinx:
  config:
    nb_render_plugin: 'default'
    nb_render_priority:
      html: ["application/vnd.jupyter.widget-view+json", "application/vnd.plotly.v1+json", "application/javascript", "text/html", "image/svg+xml", "image/png", "image/jpeg", "text/markdown", "text/latex", "text/plain"]
  extra_extensions:
    - "IPython.sphinxext.ipython_console_highlighting"
  config:
    html_js_files:
      - https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.4/require.min.js
